# -*- coding: utf-8 -*-
"""Misi Mikroplastik.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZKVRMU8-vabXfIOqCZeDZslNooxaa5MI
"""

import pandas as pd
import matplotlib.pyplot as plt
from google.colab import files
from IPython.display import display, HTML
import ipywidgets as widgets
import io
import random

# --- FUNGSI UTAMA UNTUK TAMPILAN DAN LOGIKA ---

def generate_feedback(jenis_dominan_str):
    # Logika Fakta, Rekomendasi, dan Kata Mutiara (Sama seperti sebelumnya)
    fakta, rekomendasi, img_query = "", "", ""
    # ... (Potongan kode yang memilih fakta/rekomendasi berdasarkan jenis_dominan_str) ...
    if "Botol PET" in jenis_dominan_str:
        fakta = "Fakta Mengkhawatirkan: Botol PET membutuhkan waktu sekitar 450 tahun untuk terurai. Sebagian besar botol hanya digunakan sekali!"
        rekomendasi = "Rekomendasi Penanganan: Wajibkan penggunaan botol minum (tumbler) isi ulang di seluruh area sekolah (guru dan siswa)."
        img_query = "Reusable water bottle vs single use plastic bottle"
    elif "Bungkus Snack" in jenis_dominan_str or "Plastik Film" in jenis_dominan_str:
        fakta = "Fakta Mengkhawatirkan: Bungkus berlapis (multilayer) seperti bungkus snack hampir tidak mungkin didaur ulang di Indonesia dan langsung menjadi residu."
        rekomendasi = "Rekomendasi Penanganan: Dorong siswa membawa bekal makanan ringan dari rumah dalam wadah yang dapat dipakai ulang (tupperware)."
        img_query = "Multilayer plastic packaging"
    elif "Sedotan" in jenis_dominan_str:
        fakta = "Fakta Mengkhawatirkan: Meskipun ringan, jutaan sedotan digunakan setiap hari. Karena ukurannya, sedotan adalah penyumbang mikroplastik di laut yang berbahaya bagi biota."
        rekomendasi = "Rekomendasi Penanganan: Larang penyediaan sedotan plastik di kantin dan ganti dengan sedotan kertas atau tidak sama sekali."
        img_query = "Microplastic pollution in ocean"
    elif "Styrofoam" in jenis_dominan_str or "Wadah Makanan" in jenis_dominan_str:
        fakta = "Fakta Mengkhawatirkan: Styrofoam sangat sulit terurai dan melepaskan bahan kimia berbahaya saat terpapar panas, mengancam kesehatan dan lingkungan."
        rekomendasi = "Rekomendasi Penanganan: Himbau kantin sekolah untuk tidak menggunakan wadah Styrofoam, ganti dengan piring/mangkok pakai ulang atau kotak bekal siswa."
        img_query = "Styrofoam food containers impact"
    else:
        fakta = "Fakta Mengkhawatirkan: Setiap tahun, jutaan ton plastik berakhir di TPA dan mencemari lingkungan. Perubahan dimulai dari kesadaran kita!"
        rekomendasi = "Rekomendasi Penanganan: Adakan pelatihan pemilahan sampah yang ketat (organik vs non-organik) untuk meningkatkan efektivitas daur ulang di sekolah."
        img_query = "Global plastic waste problem"

    kata_mutiara = [
        "Bumi adalah rumah kita, mari jaga ia dengan aksi nyata, bukan hanya kata-kata.",
        "Sampah adalah cerminan peradaban. Mari tunjukkan bahwa peradaban kita bersih dan bijaksana.",
        "Kita tidak mewarisi bumi dari leluhur kita; kita meminjamnya dari anak cucu kita.",
        "Masa depan hijau dimulai dengan keputusan kecil hari ini."
    ]

    return fakta, rekomendasi, random.choice(kata_mutiara), img_query

def tampilkan_tahap_solusi(nama_siswa, jenis_terdominan):
    """Menampilkan input solusi dan mengelola event submit (Enter)."""

    # 1. Tampilkan Judul Tahap 3
    display(HTML("<hr><h2>💡 Tahap 3: Merancang Solusi Berbasis Data & Laporan Akhir</h2>"))
    display(HTML(f"""
        <p>Analisis data menunjukkan bahwa **{jenis_terdominan}** adalah masalah terbesar kita.
        Sekarang, pikirkan: Apa solusi yang paling realistis untuk mengurangi **{jenis_terdominan}** di sekolah?</p>
    """))

    # 2. Inisiasi Widget (Text Input dan Output)
    solusi_input = widgets.Text(
        value='',
        placeholder='Tuliskan Solusi Utama Anda di sini, lalu tekan ENTER...',
        description='Solusi:',
        disabled=False,
        layout=widgets.Layout(width='80%')
    )
    output_akhir = widgets.Output()

    # 3. Definisikan Logika Submit
    def on_submit_solusi(sender):
        with output_akhir:
            output_akhir.clear_output()
            solusi_value = sender.value

            if not solusi_value:
                display(HTML("<p style='color:red;'><i>Mohon masukkan ide solusi (tekan Enter setelah mengetik).</i></p>"))
                return

            fakta, rekomendasi, kata_mutiara_pilihan, img_query = generate_feedback(jenis_terdominan)

            # --- APRESIASI & HASIL ---
            display(HTML(f"""
                <div style='background-color:#007bff; color:white; padding:20px; text-align:center; border-radius:10px;'>
                    <h1 style='margin:0;'>🎉 SELAMAT! {nama_siswa.upper()}! 🎉</h1>
                    <p style='font-size:1.2em;'>Anda telah berhasil menyelesaikan Proyek "Data Driven Trash Tracker"!</p>
                </div>
                <br>
                <h3>🔬 Laporan Temuan dan Apresiasi</h3>
                <div style='border: 1px solid #ced4da; padding: 15px; background-color: #f8f9fa; border-radius: 5px;'>
                    <p><b>Solusi Utama yang Anda Ajukan:</b> {solusi_value}</p>
                    <p><b>Fokus Utama Proyek Anda:</b> {jenis_terdominan}</p>
                    <hr>
                    <p style='font-weight: bold;'>🚨 {fakta}</p>
                    <p><b>Langkah Rekomendasi:</b> {rekomendasi}</p>
                    <hr>
                    <p style='font-style: italic;'>"{kata_mutiara_pilihan}"</p>
                </div>
                <p>Visualisasi Dampak dan Solusi:</p>
            """))
            display(HTML("")) #

    # 4. Hubungkan Event dan Tampilkan Widget
    solusi_input.on_submit(on_submit_solusi)
    display(solusi_input, output_akhir) # Tampilkan di bagian akhir

def run_analisis_sampah(df, nama_siswa):
    """Menganalisis data dan menampilkan visualisasi data, lalu memanggil Tahap 3."""

    display(HTML("<h2>📊 Tahap 2: Hasil Analisis Data Audit</h2>"))

    data_berat_per_jenis = df.groupby('Jenis Plastik')['Berat (gram)'].sum().sort_values(ascending=False)
    total_berat_keseluruhan = data_berat_per_jenis.sum()

    jenis_terdominan = data_berat_per_jenis.index[0] if not data_berat_per_jenis.empty else "Tidak Ada Data Plastik"

    display(HTML(f"""
        <div style='background-color:#fff3cd; border:1px solid #ffeeba; padding:10px; border-radius:5px;'>
            <b>Total Sampah Plastik yang Diaudit:</b> {total_berat_keseluruhan:.2f} gram.<br>
            <b>Jenis Paling Dominan:</b> <b>{jenis_terdominan}</b> ({data_berat_per_jenis.max():.2f} gram).<br>
        </div>
    """))

    if not data_berat_per_jenis.empty:
        # Visualisasi 1: Diagram Batang
        # ... (Visualisasi 1 code) ...
        display(HTML("<h3>1. Kontributor Utama Sampah Plastik</h3>"))
        fig1, ax1 = plt.subplots(figsize=(10, 6))
        ax1.bar(data_berat_per_jenis.index, data_berat_per_jenis.values, color=plt.cm.viridis(data_berat_per_jenis.values / total_berat_keseluruhan))
        ax1.set_title('Berat Total Sampah Plastik Berdasarkan Jenis (Gram)', fontweight='bold')
        ax1.set_xlabel('Jenis Plastik')
        ax1.set_ylabel('Berat Total (gram)')
        plt.xticks(rotation=45, ha='right')
        plt.grid(axis='y', linestyle='--')
        plt.tight_layout()
        plt.show(fig1)



        # Visualisasi 2: Diagram Lingkaran
        # ... (Visualisasi 2 code) ...
        display(HTML("<h3>2. Persentase Kontribusi</h3>"))
        fig2, ax2 = plt.subplots(figsize=(8, 8))
        data_pie = data_berat_per_jenis[data_berat_per_jenis / total_berat_keseluruhan > 0.05]
        other_berat = total_berat_keseluruhan - data_pie.sum()
        if other_berat > 0 and not data_pie.empty: data_pie['Lain-lain'] = other_berat
        if not data_pie.empty:
            ax2.pie(data_pie.values, labels=data_pie.index, autopct='%1.1f%%', startangle=140, colors=plt.cm.Set3.colors, wedgeprops={'edgecolor': 'black'})
            ax2.set_title('Persentase Kontribusi Setiap Jenis Plastik', fontweight='bold')
            ax2.axis('equal')
            plt.show(fig2)

        else: display(HTML("<p><i>Tidak cukup data plastik untuk membuat Diagram Lingkaran yang berarti.</i></p>"))
    else: display(HTML("<p><i>Tidak ada data plastik yang ditemukan untuk divisualisasikan.</i></p>"))

    # PANGGIL FUNGSI TAHAP 3 SETELAH SEMUA VISUALISASI SELESAI
    tampilkan_tahap_solusi(nama_siswa, jenis_terdominan)

# --- PROGRAM UTAMA COLAB ---

def tampilan_awal_dan_input():
    # ... (Kode Tampilan Awal sama) ...
    display(HTML("<h1>🗑️ Data Driven Trash Tracker: Misi Mikroplastik Sekolah</h1>"))
    display(HTML("<h3>Selamat Datang, Detektif Lingkungan!</h3>"))
    display(HTML("""
        <p>Proyek ini adalah investigasi ilmiah untuk mengungkap jejak sampah plastik di lingkungan sekolah kita.
        Kita akan menggunakan <b>data</b> dan <b>pemrograman Python</b> untuk mencari tahu jenis plastik apa yang paling dominan
        dan di mana 'hotspot' sampah berada.</p>

        <h4>🎯 Tujuan Proyek</h4>
        <ul>
            <li><b>Menganalisis:</b> Mengolah data audit sampah menjadi informasi visual.</li>
            <li><b>Memahami:</b> Mengidentifikasi sumber utama dan jenis plastik yang paling berbahaya (potensi mikroplastik).</li>
            <li><b>Bertindak:</b> Merancang solusi berbasis data untuk mengurangi sampah di sekolah.</li>
        </ul>
    """))

    nama_siswa_input = widgets.Text(value='', placeholder='Masukkan Nama Anda / Nama Kelompok...', description='Nama:', disabled=False)
    output_nama = widgets.Output()

    def on_submit_nama(sender):
        with output_nama:
            output_nama.clear_output()
            if nama_siswa_input.value:
                display(HTML(f"🎉 Halo, <b>{nama_siswa_input.value}</b>! Siap memulai misi? Lanjutkan ke Tahap 1."))
            else:
                display(HTML("<i>Mohon masukkan nama kelompok Anda.</i>"))

    nama_siswa_input.observe(on_submit_nama, names='value')
    display(nama_siswa_input, output_nama)
    return nama_siswa_input

if __name__ == "__main__":
    nama_siswa_widget = tampilan_awal_dan_input()

    display(HTML("<hr><h2>📥 Tahap 1: Unggah Data Audit Sampah</h2>"))
    display(HTML("Klik tombol di bawah untuk mengunggah file Excel Anda (misal: <code>data_sampah.xlsx</code>)."))

    upload_button = widgets.Button(description="Upload File Excel (.xlsx)")
    output_upload = widgets.Output()
    display(upload_button, output_upload)

    def on_upload_clicked(b):
        with output_upload:
            output_upload.clear_output()

            current_nama_siswa = nama_siswa_widget.value
            if not current_nama_siswa:
                display(HTML("<p style='color:red;'><b>Mohon masukkan nama Anda/kelompok terlebih dahulu di atas!</b></p>"))
                return

            uploaded = files.upload()
            if not uploaded:
                display(HTML("<p style='color:red;'>Tidak ada file yang diunggah. Mohon coba lagi.</p>"))
                return

            file_name = list(uploaded.keys())[0]
            try:
                df = pd.read_excel(io.BytesIO(uploaded[file_name]))

                kolom_wajib = ['Tanggal', 'Jenis Plastik', 'Berat (gram)', 'Sumber (Kantin/Kelas)']
                if not all(col in df.columns for col in kolom_wajib):
                    display(HTML("⚠️ <span style='color:red;'>Error: Kolom Excel tidak sesuai!</span> Pastikan kolomnya adalah: Tanggal, Jenis Plastik, Berat (gram), Sumber (Kantin/Kelas)."))
                    return

                display(HTML(f"<p style='color:green;'>✅ File <b>{file_name}</b> berhasil diunggah.</p>"))
                display(HTML("<p><b>5 Baris Data Pertama Anda:</b></p>"))
                display(df.head())

                run_analisis_sampah(df, current_nama_siswa)

            except Exception as e:
                display(HTML(f"<p style='color:red;'>Terjadi kesalahan saat memproses file: {e}</p>"))

    upload_button.on_click(on_upload_clicked)